import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import Store from "@/components/Store";
import Button from "@/components/Button";


export default function Home() {
  return (
    <>
      <Head>
        <title>BCIT Book Store</title>
        <meta name="All online pick-up orders are available at the Burnaby Campus Bookstore
        (SE2). Please allow 2-3 business days for order processing." content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
        <main className={`${styles.main}`}>
          <Store/>
        </main>
      <Footer/>
    </>
  );
}
